# Generated by Django 4.2.29 on 2026-05-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
