# Generated by Django 4.2.29 on 2026-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_guest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('ceremony', 'ceremony'), ('reception', 'reception')], max_length=10),
        ),
    ]
