# Generated by Django 4.2.29 on 2026-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_alter_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending_ceremony',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='attending_reception',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
